spring:
   profiles:
      active:
      - dev
---
server:
   port: 8001
spring:
   profiles: dev
   application:
      name: microservicecloud-config-dep-client
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb1   
    username: root
    password: 111
    dbcp2:  
      min-idle: 5                  
      initial-size: 5               
      max-total: 5                  
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.springclouddemo.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

eureka:
   client:
      service-url:
         defaultZone: http://localhost:7001/eureka/

info:
  app.name: microservicecloud_dept
  company.name: www.xiaohucloud.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
   port: 8001
spring:
   profiles: dev
   application:
      name: microservicecloud-config-dep-client
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb2 
    username: root
    password: 111
    dbcp2:  
      min-idle: 5                  
      initial-size: 5               
      max-total: 5                  
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.springclouddemo.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

eureka:
   client:
      service-url:
         defaultZone: http://localhost:7001/eureka/

info:
  app.name: microservicecloud_dept
  company.name: www.xiaohucloud.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
